# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Class for evaluating programs proposed by the Sampler."""
import ast
import sys
import os
import json
import time
from datetime import datetime
from collections.abc import Sequence
import copy
from typing import Any

from ..implementation import code_manipulation
from ..implementation import programs_database


class _FunctionLineVisitor(ast.NodeVisitor):
  """Visitor that finds the last line number of a function with a given name."""

  def __init__(self, target_function_name: str) -> None:
    self._target_function_name: str = target_function_name
    self._function_end_line: int | None = None

  def visit_FunctionDef(self, node: Any) -> None:  # pylint: disable=invalid-name
    """Collects the end line number of the target function."""
    if node.name == self._target_function_name:
      self._function_end_line = node.end_lineno
    self.generic_visit(node)

  @property
  def function_end_line(self) -> int:
    """Line number of the final line of function `target_function_name`."""
    assert self._function_end_line is not None  # Check internal correctness.
    return self._function_end_line


def _trim_function_body(generated_code: str) -> str:
  """Extracts the body of the generated function, trimming anything after it."""
  if not generated_code:
    return ''
  
  # 不为生成的代码添加缩进！sample本身已经有缩进了
  code = f'def fake_function_header():\n{generated_code}'
  
  tree = None
  # We keep trying and deleting code from the end until the parser succeeds.
  while tree is None:
    try:
      tree = ast.parse(code)
    except SyntaxError as e:
      code = '\n'.join(code.splitlines()[:e.lineno - 1])
  if not code:
    # Nothing could be saved from `generated_code`
    return ''

  visitor = _FunctionLineVisitor('fake_function_header')
  visitor.visit(tree)
  body_lines = code.splitlines()[1:visitor.function_end_line]
  
  # 不移除缩进！Function对象期望函数体已经缩进
  trimmed_body = '\n'.join(body_lines)
  
  return trimmed_body + '\n\n'


def _sample_to_program(
    generated_code: str,
    version_generated: int | None,
    template: code_manipulation.Program,
    function_to_evolve: str,
) -> tuple[code_manipulation.Function, str]:
  """Returns the compiled generated function and the full runnable program."""
  body = _trim_function_body(generated_code)
  if version_generated is not None:
    body = code_manipulation.rename_function_calls(
        body,
        f'{function_to_evolve}_v{version_generated}',
        function_to_evolve)

  program = copy.deepcopy(template)
  evolved_function = program.get_function(function_to_evolve)
  
  # 不需要添加缩进！_trim_function_body已经处理了缩进
  
  evolved_function.body = body
  return evolved_function, str(program)


class Sandbox:
  """Sandbox for executing generated code."""

  def run(
      self,
      program: str,
      function_to_run: str,
      test_input: str,
      timeout_seconds: int,
  ) -> tuple[Any, bool]:
    """Returns `function_to_run(test_input)` and whether execution succeeded."""
    raise NotImplementedError(
        'Must provide a sandbox for executing untrusted code.')


def _calls_ancestor(program: str, function_to_evolve: str) -> bool:
  """Returns whether the generated function is calling an earlier version."""
  for name in code_manipulation.get_functions_called(program):
    # In `program` passed into this function the most recently generated
    # function has already been renamed to `function_to_evolve` (wihout the
    # suffix). Therefore any function call starting with `function_to_evolve_v`
    # is a call to an ancestor function.
    if name.startswith(f'{function_to_evolve}_v'):
      return True
  return False


class Evaluator:
  """Class that analyses functions generated by LLMs."""

  def __init__(
      self,
      database: programs_database.ProgramsDatabase,
      template: code_manipulation.Program,
      function_to_evolve: str,
      function_to_run: str,
      inputs: Sequence[Any],
      timeout_seconds: int = 30,
  ):
    self._database = database
    self._template = template
    self._function_to_evolve = function_to_evolve
    self._function_to_run = function_to_run
    self._inputs = inputs
    self._timeout_seconds = timeout_seconds
    self._sandbox = Sandbox()
    
    # 进化记录相关
    self.evolution_log = []
    self.generation_count = 0
    self.log_dir = 'funsearch_evolution'
    os.makedirs(self.log_dir, exist_ok=True)

  def analyse(
      self,
      sample: str,
      island_id: int | None,
      version_generated: int | None,
  ) -> None:
    """Compiles the sample into a program and executes it on test inputs."""
    # 将新策略注册到对应的 Island
    new_function, program = _sample_to_program(
        sample, version_generated, self._template, self._function_to_evolve)
    
    # 为每个 Island 评估其自己的策略
    scores_per_test = {}
    island_results = []
    
    start_time = time.time()
    
    for current_input in self._inputs:
      # 获取当前输入对应的 island_id
      current_island_id = current_input.get('island_id', 0)
      
      # 从数据库获取该 Island 的最佳策略
      island_program = self._get_island_program(current_island_id)
      
      # 使用该 Island 自己的策略进行评估
      if island_program is not None:
          test_output = self._evaluate_strategy(island_program, current_input, current_island_id)
      else:
          # 如果没有找到，使用新策略
          test_output = self._evaluate_strategy(program, current_input, current_island_id)
      
      runs_ok = True  # 假设运行成功
      
      if (runs_ok and test_output is not None):
        if not isinstance(test_output, (int, float)):
          raise ValueError('@function.run did not return an int/float score.')
        # 使用字符串键而不是dict键
        input_key = str(current_input)
        scores_per_test[input_key] = test_output
        
        # 记录每个Island的结果
        # 提取策略函数代码部分，而不是完整程序
        def extract_strategy_code(program_str):
            """提取策略函数代码"""
            lines = program_str.split('\n')
            in_strategy = False
            strategy_lines = []
            for line in lines:
                if 'def investment_strategy(' in line:
                    in_strategy = True
                    continue
                if in_strategy:
                    if line.strip().startswith('def ') or line.strip().startswith('@'):
                        break
                    strategy_lines.append(line)
            return '\n'.join(strategy_lines)
        
        # 提取策略代码
        strategy_code = extract_strategy_code(island_program if island_program is not None else program)
        
        island_results.append({
            'island_id': current_island_id,
            'score': test_output,
            'strategy_code': strategy_code[:500] + '...' if len(strategy_code) > 500 else strategy_code
        })
    
    # 将新策略注册到对应的 Island
    if scores_per_test:
      self._database.register_program(new_function, island_id, scores_per_test)
    
    # 记录进化过程
    self.generation_count += 1
    generation_data = {
        'generation': self.generation_count,
        'timestamp': datetime.now().isoformat(),
        'execution_time': time.time() - start_time,
        'generated_code': sample,
        'island_results': island_results,
        'best_score': max(scores_per_test.values()) if scores_per_test else 0,
        'average_score': sum(scores_per_test.values()) / len(scores_per_test) if scores_per_test else 0
    }
    
    self.evolution_log.append(generation_data)
    
    # 保存进化记录
    log_file = os.path.join(self.log_dir, f'evolution_log.json')
    with open(log_file, 'w', encoding='utf-8') as f:
        json.dump(self.evolution_log, f, ensure_ascii=False, indent=2)
    
    # 保存每代的详细数据
    generation_file = os.path.join(self.log_dir, f'generation_{self.generation_count}.json')
    with open(generation_file, 'w', encoding='utf-8') as f:
        json.dump(generation_data, f, ensure_ascii=False, indent=2)
  
  def _get_island_program(self, island_id: int) -> str | None:
    """获取指定 Island 的最佳策略程序"""
    try:
      # 从数据库获取该 Island 的最佳策略
      best_program = self._database._best_program_per_island[island_id]
      if best_program is not None:
        # 返回策略程序
        return str(best_program)
      return None
    except Exception:
      return None
  
  def _evaluate_strategy(self, program: str, current_input: dict, island_id: int = 0) -> float:
    """Custom evaluation function for investment strategies."""
    # 导入自定义评估函数
    project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../"))
    if project_path not in sys.path:
        sys.path.insert(0, project_path)
    
    # 动态导入funsearch_specification_enhanced模块
    try:
        import funsearch_specification_enhanced as fs_spec
    except ImportError:
        # 如果增强版不存在，回退到原版
        import funsearch_specification as fs_spec
    
    # 从模块获取evaluate_strategy函数
    evaluate_strategy_func = fs_spec.evaluate_strategy
    
    # 从模块获取原始investment_strategy函数
    original_investment_strategy = fs_spec.investment_strategy
    
    # 动态执行program，获取新的investment_strategy函数
    try:
        # 导入所有需要的模块
        import numpy as np
        import torch
        import os as os_module
        import sys as sys_module
        import pandas as pd
        import matplotlib
        import platform
        import yaml
        from datetime import datetime
        
        # 创建完整的命名空间
        temp_namespace = {
            '__name__': '__main__',
            '__file__': 'generated_program.py',
            '__builtins__': __builtins__,
            'np': np,
            'torch': torch,
            'os': os_module,
            'sys': sys_module,
            'pd': pd,
            'matplotlib': matplotlib,
            'platform': platform,
            'yaml': yaml,
            'datetime': datetime,
        }
        

        
        # 使用compile预编译，避免缩进错误
        compiled_program = compile(program, '<string>', 'exec')
        exec(compiled_program, temp_namespace)
        

        
        # 获取新的investment_strategy函数（优先检查带版本号的新策略）
        new_investment_strategy = None
        # 首先检查带版本号的新策略（v0, v1, v2等），这些是新生成的策略
        for func_name in ['investment_strategy_v2', 'investment_strategy_v1', 'investment_strategy_v0', 'investment_strategy']:
            if func_name in temp_namespace:
                new_investment_strategy = temp_namespace[func_name]
                print(f"[Evaluator] 使用新策略 {func_name} (island={current_input.get('island_id', 0)})")
                break
        
        strategy_func = original_investment_strategy
        
        if new_investment_strategy is not None:
            # 调试：测试策略函数是否返回有效值
            test_market_state = np.random.rand(10, 5).astype(np.float32)
            test_portfolio = np.ones(5) / 5
            new_strategy_valid = False
            
            try:
                # 首先用None参数测试，因为新策略应该正确处理portfolio为None的情况
                test_result_none = new_investment_strategy(test_market_state, None)
                if test_result_none is None:
                    print(f"[Evaluator] 新策略(None参数)返回 None，尝试非None参数")
                elif not isinstance(test_result_none, np.ndarray):
                    print(f"[Evaluator] 新策略(None参数)返回类型错误: {type(test_result_none)}，尝试非None参数")
                else:
                    # 简化输出，不显示具体权重
                    print(f"[Evaluator] 新策略(None参数)测试通过")
                    new_strategy_valid = True
            except Exception as e:
                print(f"[Evaluator] 新策略(None参数)测试失败: {e}，尝试非None参数")
            
            # 如果None参数测试失败，尝试非None参数
            if not new_strategy_valid:
                try:
                    test_result = new_investment_strategy(test_market_state, test_portfolio)
                    if test_result is None:
                        print(f"[Evaluator] 新策略(非None参数)返回 None，使用原始策略")
                    elif not isinstance(test_result, np.ndarray):
                        print(f"[Evaluator] 新策略(非None参数)返回类型错误: {type(test_result)}，使用原始策略")
                    else:
                        # 简化输出，不显示具体权重
                        print(f"[Evaluator] 新策略(非None参数)测试通过")
                        new_strategy_valid = True
                except Exception as e:
                    print(f"[Evaluator] 新策略(非None参数)测试失败: {e}，使用原始策略")
            
            # 如果新策略在任一测试中通过，就使用新策略
            if new_strategy_valid:
                strategy_func = new_investment_strategy
            else:
                print(f"[Evaluator] 新策略测试失败，使用原始策略 (island={current_input.get('island_id', 0)})")
        else:
            print(f"[Evaluator] 新策略不存在，使用原始策略 (island={current_input.get('island_id', 0)})")
    except Exception as e:
        print(f"[Evaluator] 执行program失败: {e}，使用原始策略 (island={current_input.get('island_id', 0)})")
        strategy_func = original_investment_strategy
    
    # 评估策略
    return evaluate_strategy_func({
        'strategy_func': strategy_func,
        'window_size': current_input.get('window_size', 20),
        'island_id': current_input.get('island_id', 0)
    })
  
